'use strict';

module.exports = [
	{
		name: 'AirSync',
		tags: [
			{ name: 'Sync', token: 0x05 },
			{ name: 'Responses', token: 0x06 },
			{ name: 'Add', token: 0x07 },
			{ name: 'Change', token: 0x08 },
			{ name: 'Delete', token: 0x09 },
			{ name: 'Fetch', token: 0x0a },
			{ name: 'SyncKey', token: 0x0b },
			{ name: 'ClientId', token: 0x0c },
			{ name: 'ServerId', token: 0x0d },
			{ name: 'Status', token: 0x0e },
			{ name: 'Collection', token: 0x0f },
			{ name: 'Class', token: 0x10 },
			{ name: 'CollectionId', token: 0x12 },
			{ name: 'GetChanges', token: 0x13 },
			{ name: 'MoreAvailable', token: 0x14 },
			{ name: 'WindowSize', token: 0x15 },
			{ name: 'Commands', token: 0x16 },
			{ name: 'Options', token: 0x17 },
			{ name: 'FilterType', token: 0x18 },
			{ name: 'Truncation', token: 0x19 },
			{ name: 'Conflict', token: 0x1b },
			{ name: 'Collections', token: 0x1c },
			{ name: 'ApplicationData', token: 0x1d },
			{ name: 'DeletesAsMoves', token: 0x1e },
			{ name: 'Supported', token: 0x20 },
			{ name: 'SoftDelete', token: 0x21 },
			{ name: 'MIMESupport', token: 0x22 },
			{ name: 'MIMETruncation', token: 0x23 },
			{ name: 'Wait', token: 0x24 },
			{ name: 'Limit', token: 0x25 },
			{ name: 'Partial', token: 0x26 },
			{ name: 'ConversationMode', token: 0x27 },
			{ name: 'MaxItems', token: 0x28 },
			{ name: 'HeartbeatInterval', token: 0x29 }
		]
	},
	{
		name: 'Contacts',
		tags: []
	},
	{
		name: 'Email',
		tags: []
	},
	{
		name: 'AirNotify',
		tags: []
	},
	{
		name: 'Calendar',
		tags: [
			{ name: 'Timezone', token: 0x05 },
			{ name: 'AllDayEvent', token: 0x06 },
			{ name: 'Attendees', token: 0x07 },
			{ name: 'Attendee', token: 0x08 },
			{ name: 'Email', token: 0x09 },
			{ name: 'Name', token: 0x0a },
			{ name: 'Body', token: 0x0b },
			{ name: 'BodyTruncated', token: 0x0c },
			{ name: 'BusyStatus', token: 0x0d },
			{ name: 'Categories', token: 0x0e },
			{ name: 'Category', token: 0x0f },
			{ name: 'DtStamp', token: 0x11 },
			{ name: 'EndTime', token: 0x12 },
			{ name: 'Exception', token: 0x13 },
			{ name: 'Exceptions', token: 0x14 },
			{ name: 'Deleted', token: 0x15 },
			{ name: 'ExceptionStartTime', token: 0x16 },
			{ name: 'Location', token: 0x17 },
			{ name: 'MeetingStatus', token: 0x18 },
			{ name: 'OrganizerEmail', token: 0x19 },
			{ name: 'OrganizerName', token: 0x1a },
			{ name: 'Recurrence', token: 0x1b },
			{ name: 'Type', token: 0x1c },
			{ name: 'Until', token: 0x1d },
			{ name: 'Occurrences', token: 0x1e },
			{ name: 'Interval', token: 0x1f },
			{ name: 'DayOfWeek', token: 0x20 },
			{ name: 'DayOfMonth', token: 0x21 },
			{ name: 'WeekOfMonth', token: 0x22 },
			{ name: 'MonthOfYear', token: 0x23 },
			{ name: 'Reminder', token: 0x24 },
			{ name: 'Sensitivity', token: 0x25 },
			{ name: 'Subject', token: 0x26 },
			{ name: 'StartTime', token: 0x27 },
			{ name: 'UID', token: 0x28 },
			{ name: 'AttendeeStatus', token: 0x29 },
			{ name: 'AttendeeType', token: 0x2a },
			{ name: 'DisallowNewTimeProposal', token: 0x33 },
			{ name: 'ResponseRequested', token: 0x34 },
			{ name: 'AppointmentReplyTime', token: 0x35 },
			{ name: 'ResponseType', token: 0x36 },
			{ name: 'CalendarType', token: 0x37 },
			{ name: 'IsLeapMonth', token: 0x38 },
			{ name: 'FirstDayOfWeek', token: 0x39 },
			{ name: 'OnlineMeetingConfLink', token: 0x3a },
			{ name: 'OnlineMeetingExternalLink', token: 0x3b },
			{ name: 'ClientUid', token: 0x3c }
		]
	},
	{
		name: 'Move',
		tags: []
	},
	{
		name: 'GetItemEstimate',
		tags: []
	},
	{
		name: 'FolderHierarchy',
		tags: [
			{ name: 'Folders', token: 0x05 },
			{ name: 'Folder', token: 0x06 },
			{ name: 'DisplayName', token: 0x07 },
			{ name: 'ServerId', token: 0x08 },
			{ name: 'ParentId', token: 0x09 },
			{ name: 'Type', token: 0x0a },
			{ name: 'Status', token: 0x0c },
			{ name: 'Changes', token: 0x0e },
			{ name: 'Add', token: 0x0f },
			{ name: 'Delete', token: 0x10 },
			{ name: 'Update', token: 0x11 },
			{ name: 'SyncKey', token: 0x12 },
			{ name: 'FolderCreate', token: 0x13 },
			{ name: 'FolderDelete', token: 0x14 },
			{ name: 'FolderUpdate', token: 0x15 },
			{ name: 'FolderSync', token: 0x16 },
			{ name: 'Count', token: 0x17 }
		]
	},
	{
		name: 'MeetingResponse',
		tags: []
	},
	{
		name: 'Tasks',
		tags: []
	},
	{
		name: 'ResolveRecipients',
		tags: []
	},
	{
		name: 'ValidateCert',
		tags: []
	},
	{
		name: 'Contacts2',
		tags: []
	},
	{
		name: 'Ping',
		tags: []
	},
	{
		name: 'Provision',
		tags: [
			{ name: 'Provision', token: 0x05 },
			{ name: 'Policies', token: 0x06 },
			{ name: 'Policy', token: 0x07 },
			{ name: 'PolicyType', token: 0x08 },
			{ name: 'PolicyKey', token: 0x09 },
			{ name: 'Data', token: 0x0a },
			{ name: 'Status', token: 0x0b },
			{ name: 'RemoteWipe', token: 0x0c },
			{ name: 'EASProvisionDoc', token: 0x0d },
			{ name: 'DevicePasswordEnabled', token: 0x0e },
			{ name: 'AlphanumericDevicePasswordRequired', token: 0x0f },
			{ name: 'RequireStorageCardEncryption', token: 0x10 },
			{ name: 'PasswordRecoveryEnabled', token: 0x11 },
			{ name: 'AttachmentsEnabled', token: 0x13 },
			{ name: 'MinDevicePasswordLength', token: 0x14 },
			{ name: 'MaxInactivityTimeDeviceLock', token: 0x15 },
			{ name: 'MaxDevicePasswordFailedAttempts', token: 0x16 },
			{ name: 'MaxAttachmentSize', token: 0x17 },
			{ name: 'AllowSimpleDevicePassword', token: 0x18 },
			{ name: 'DevicePasswordExpiration', token: 0x19 },
			{ name: 'DevicePasswordHistory', token: 0x1a },
			{ name: 'AllowStorageCard', token: 0x1b },
			{ name: 'AllowCamera', token: 0x1c },
			{ name: 'RequireDeviceEncryption', token: 0x1d },
			{ name: 'AllowUnsignedApplications', token: 0x1e },
			{ name: 'AllowUnsignedInstallationPackages', token: 0x1f },
			{ name: 'MinDevicePasswordComplexCharacters', token: 0x20 },
			{ name: 'AllowWiFi', token: 0x21 },
			{ name: 'AllowTextMessaging', token: 0x22 },
			{ name: 'AllowPOPIMAPEmail', token: 0x23 },
			{ name: 'AllowBluetooth', token: 0x24 },
			{ name: 'AllowIrDA', token: 0x25 },
			{ name: 'RequireManaualSyncWhenRoaming', token: 0x26 },
			{ name: 'AllowDesktopSync', token: 0x27 },
			{ name: 'MaxCalendarAgeFilter', token: 0x28 },
			{ name: 'AllowHTMLEmail', token: 0x29 },
			{ name: 'MaxEmailAgeFilter', token: 0x2a },
			{ name: 'MaxEmailBodyTruncationSize', token: 0x2b },
			{ name: 'MaxEmailHTMLBodyTruncationSize', token: 0x2c },
			{ name: 'RequireSignedSMIMEMessages', token: 0x2d },
			{ name: 'RequireEncryptedSMIMEMessages', token: 0x2e },
			{ name: 'RequireSignedSMIMEAlgorithm', token: 0x2f },
			{ name: 'RequireEncryptionSMIMEAlgorithm', token: 0x30 },
			{ name: 'AllowSMIMEEncryptionAlgorithmNegotiation', token: 0x31 },
			{ name: 'AllowSMIMESoftCerts', token: 0x32 },
			{ name: 'AllowBrowser', token: 0x33 },
			{ name: 'AllowConsumerEmail', token: 0x34 },
			{ name: 'AllowRemoteDesktop', token: 0x35 },
			{ name: 'AllowInternetSharing', token: 0x36 },
			{ name: 'UnapprovedInROMApplicationList', token: 0x37 },
			{ name: 'ApplicationName', token: 0x38 },
			{ name: 'ApprovedApplicationList', token: 0x39 },
			{ name: 'Hash', token: 0x3a }
		]
	},
	{
		name: 'Search',
		tags: []
	},
	{
		name: 'GAL',
		tags: []
	},
	{
		name: 'AirSyncBase',
		tags: [
			{ name: 'BodyPreference', token: 0x05 },
			{ name: 'Type', token: 0x06 },
			{ name: 'TruncationSize', token: 0x07 },
			{ name: 'AllOrNone', token: 0x08 },
			{ name: 'Body', token: 0x0a },
			{ name: 'Data', token: 0x0b },
			{ name: 'EstimatedDataSize', token: 0x0c },
			{ name: 'Truncated', token: 0x0d },
			{ name: 'Attachments', token: 0x0e },
			{ name: 'Attachment', token: 0x0f },
			{ name: 'DisplayName', token: 0x10 },
			{ name: 'FileReference', token: 0x11 },
			{ name: 'Method', token: 0x12 },
			{ name: 'ContentId', token: 0x13 },
			{ name: 'ContentLocation', token: 0x14 },
			{ name: 'IsInline', token: 0x15 },
			{ name: 'NativeBodyType', token: 0x16 },
			{ name: 'ContentType', token: 0x17 },
			{ name: 'Preview', token: 0x18 },
			{ name: 'BodyPartPreference', token: 0x19 },
			{ name: 'BodyPart', token: 0x1a },
			{ name: 'Status', token: 0x1b },
			{ name: 'Add', token: 0x1c },
			{ name: 'Delete', token: 0x1d },
			{ name: 'ClientId', token: 0x1e },
			{ name: 'Content', token: 0x1f },
			{ name: 'Location', token: 0x20 },
			{ name: 'Annotation', token: 0x21 },
			{ name: 'Street', token: 0x22 },
			{ name: 'City', token: 0x23 },
			{ name: 'State', token: 0x24 },
			{ name: 'Country', token: 0x25 },
			{ name: 'PostalCode', token: 0x26 },
			{ name: 'Latitude', token: 0x27 },
			{ name: 'Longitude', token: 0x28 },
			{ name: 'Accuracy', token: 0x29 },
			{ name: 'Altitude', token: 0x2a },
			{ name: 'AltitudeAccuracy', token: 0x2b },
			{ name: 'LocationUri', token: 0x2c },
			{ name: 'InstanceId', token: 0x2d }
		]
	},
	{
		name: 'Settings',
		tags: [
			{ name: 'Settings', token: 0x05 },
			{ name: 'Status', token: 0x06 },
			{ name: 'Get', token: 0x07 },
			{ name: 'Set', token: 0x08 },
			{ name: 'Oof', token: 0x09 },
			{ name: 'OofState', token: 0x0a },
			{ name: 'StartTime', token: 0x0b },
			{ name: 'EndTime', token: 0x0c },
			{ name: 'OofMessage', token: 0x0d },
			{ name: 'AppliesToInternal', token: 0x0e },
			{ name: 'AppliesToExternalKnown', token: 0x0f },
			{ name: 'AppliesToExternalUnknown', token: 0x10 },
			{ name: 'Enabled', token: 0x11 },
			{ name: 'ReplyMessage', token: 0x12 },
			{ name: 'BodyType', token: 0x13 },
			{ name: 'DevicePassword', token: 0x14 },
			{ name: 'Password', token: 0x15 },
			{ name: 'DeviceInformation', token: 0x16 },
			{ name: 'Model', token: 0x17 },
			{ name: 'IMEI', token: 0x18 },
			{ name: 'FriendlyName', token: 0x19 },
			{ name: 'OS', token: 0x1a },
			{ name: 'OSLanguage', token: 0x1b },
			{ name: 'PhoneNumber', token: 0x1c },
			{ name: 'UserInformation', token: 0x1d },
			{ name: 'EmailAddresses', token: 0x1e },
			{ name: 'SMTPAddress', token: 0x1f },
			{ name: 'UserAgent', token: 0x20 },
			{ name: 'EnableOutboundSMS', token: 0x21 },
			{ name: 'MobileOperator', token: 0x22 },
			{ name: 'PrimarySmtpAddress', token: 0x23 },
			{ name: 'Accounts', token: 0x24 },
			{ name: 'Account', token: 0x25 },
			{ name: 'AccountId', token: 0x26 },
			{ name: 'AccountName', token: 0x27 },
			{ name: 'UserDisplayName', token: 0x28 },
			{ name: 'SendDisabled', token: 0x29 },
			{ name: 'RightsManagementInformation', token: 0x2b }
		]
	}
];