'use strict';

module.exports = [
	{
		name: 'AirSync',
		tags: [
			{ name: 'Sync', token: 0x05 },
			{ name: 'Responses', token: 0x06 },
			{ name: 'Add', token: 0x07 },
			{ name: 'Change', token: 0x08 },
			{ name: 'Delete', token: 0x09 },
			{ name: 'Fetch', token: 0x0a },
			{ name: 'SyncKey', token: 0x0b },
			{ name: 'ClientId', token: 0x0c },
			{ name: 'ServerId', token: 0x0d },
			{ name: 'Status', token: 0x0e },
			{ name: 'Collection', token: 0x0f },
			{ name: 'Class', token: 0x10 },
			{ name: 'CollectionId', token: 0x12 },
			{ name: 'GetChanges', token: 0x13 },
			{ name: 'MoreAvailable', token: 0x14 },
			{ name: 'WindowSize', token: 0x15 },
			{ name: 'Commands', token: 0x16 },
			{ name: 'Options', token: 0x17 },
			{ name: 'FilterType', token: 0x18 },
			{ name: 'Truncation', token: 0x19 },
			{ name: 'Conflict', token: 0x1b },
			{ name: 'Collections', token: 0x1c },
			{ name: 'ApplicationData', token: 0x1d },
			{ name: 'DeletesAsMoves', token: 0x1e },
			{ name: 'Supported', token: 0x20 },
			{ name: 'SoftDelete', token: 0x21 },
			{ name: 'MIMESupport', token: 0x22 },
			{ name: 'MIMETruncation', token: 0x23 },
			{ name: 'Wait', token: 0x24 },
			{ name: 'Limit', token: 0x25 },
			{ name: 'Partial', token: 0x26 },
			{ name: 'ConversationMode', token: 0x27 },
			{ name: 'MaxItems', token: 0x28 },
			{ name: 'HeartbeatInterval', token: 0x29 }
		]
	},
	{
		name: 'Contacts',
		tags: [
			{ name: 'Anniversary', token: 0x05 },
			{ name: 'AssistantName', token: 0x06 },
			{ name: 'AssistantPhoneNumber', token: 0x07 },
			{ name: 'Birthday', token: 0x08 },
			{ name: 'Body', token: 0x09 },
			{ name: 'BodySize', token: 0x0a },
			{ name: 'BodyTruncated', token: 0x0b },
			{ name: 'Business2PhoneNumber', token: 0x0c },
			{ name: 'BusinessAddressCity', token: 0x0d },
			{ name: 'BusinessAddressCountry', token: 0x0e },
			{ name: 'BusinessAddressPostalCode', token: 0x0f },
			{ name: 'BusinessAddressState', token: 0x10 },
			{ name: 'BusinessAddressStreet', token: 0x11 },
			{ name: 'BusinessFaxNumber', token: 0x12 },
			{ name: 'BusinessPhoneNumber', token: 0x13 },
			{ name: 'CarPhoneNumber', token: 0x14 },
			{ name: 'Categories', token: 0x15 },
			{ name: 'Category', token: 0x16 },
			{ name: 'Children', token: 0x17 },
			{ name: 'Child', token: 0x18 },
			{ name: 'CompanyName', token: 0x19 },
			{ name: 'Department', token: 0x1a },
			{ name: 'Email1Address', token: 0x1b },
			{ name: 'Email2Address', token: 0x1c },
			{ name: 'Email3Address', token: 0x1d },
			{ name: 'FileAs', token: 0x1e },
			{ name: 'FirstName', token: 0x1f },
			{ name: 'Home2PhoneNumber', token: 0x20 },
			{ name: 'HomeAddressCity', token: 0x21 },
			{ name: 'HomeAddressCountry', token: 0x22 },
			{ name: 'HomeAddressPostalCode', token: 0x23 },
			{ name: 'HomeAddressState', token: 0x24 },
			{ name: 'HomeAddressStreet', token: 0x25 },
			{ name: 'HomeFaxNumber', token: 0x26 },
			{ name: 'HomePhoneNumber', token: 0x27 },
			{ name: 'JobTitle', token: 0x28 },
			{ name: 'LastName', token: 0x29 },
			{ name: 'MiddleName', token: 0x2a },
			{ name: 'MobilePhoneNumber', token: 0x2b },
			{ name: 'OfficeLocation', token: 0x2c },
			{ name: 'OtherAddressCity', token: 0x2d },
			{ name: 'OtherAddressCountry', token: 0x2e },
			{ name: 'OtherAddressPostalCode', token: 0x2f },
			{ name: 'OtherAddressState', token: 0x30 },
			{ name: 'OtherAddressStreet', token: 0x31 },
			{ name: 'PagerNumber', token: 0x32 },
			{ name: 'RadioPhoneNumber', token: 0x33 },
			{ name: 'Spouse', token: 0x34 },
			{ name: 'Suffix', token: 0x35 },
			{ name: 'Title', token: 0x36 },
			{ name: 'WebPage', token: 0x37 },
			{ name: 'YomiCompanyName', token: 0x38 },
			{ name: 'YomiFirstName', token: 0x39 },
			{ name: 'YomiLastName', token: 0x3a },
			{ name: 'Picture', token: 0x3c },
			{ name: 'Alias', token: 0x3d },
			{ name: 'WeightedRank', token: 0x3e}
		]
	},
	{
		name: 'Email',
		tags: [
			{ name: 'Attachment', token: 0x05 },
			{ name: 'Attachments', token: 0x06 },
			{ name: 'AttName', token: 0x07 },
			{ name: 'AttSize', token: 0x08 },
			{ name: 'AttOid', token: 0x09 },
			{ name: 'AttMethod', token: 0x0a },
			{ name: 'Body', token: 0x0c },
			{ name: 'BodySize', token: 0x0d },
			{ name: 'BodyTruncated', token: 0x0e },
			{ name: 'DateReceived', token: 0x0f },
			{ name: 'DisplayName', token: 0x10 },
			{ name: 'DisplayTo', token: 0x11 },
			{ name: 'Importance', token: 0x12 },
			{ name: 'MessageClass', token: 0x13 },
			{ name: 'Subject', token: 0x14 },
			{ name: 'Read', token: 0x15 },
			{ name: 'To', token: 0x16 },
			{ name: 'Cc', token: 0x17 },
			{ name: 'From', token: 0x18 },
			{ name: 'ReplyTo', token: 0x19 },
			{ name: 'AllDayEvent', token: 0x1a },
			{ name: 'Categories', token: 0x1b },
			{ name: 'Category', token: 0x1c },
			{ name: 'DtStamp', token: 0x1d },
			{ name: 'EndTime', token: 0x1e },
			{ name: 'InstanceType', token: 0x1f },
			{ name: 'BusyStatus', token: 0x20 },
			{ name: 'Location', token: 0x21 },
			{ name: 'MeetingRequest', token: 0x22 },
			{ name: 'Organizer', token: 0x23 },
			{ name: 'RecurrenceId', token: 0x24 },
			{ name: 'Reminder', token: 0x25 },
			{ name: 'ResponseRequested', token: 0x26 },
			{ name: 'Recurrences', token: 0x27 },
			{ name: 'Recurrence', token: 0x28 },
			{ name: 'Type', token: 0x29 },
			{ name: 'Until', token: 0x2a },
			{ name: 'Occurrences', token: 0x2b },
			{ name: 'Interval', token: 0x2c },
			{ name: 'DayOfWeek', token: 0x2d },
			{ name: 'DayOfMonth', token: 0x2e },
			{ name: 'WeekOfMonth', token: 0x2f },
			{ name: 'MonthOfYear', token: 0x30 },
			{ name: 'StartTime', token: 0x31 },
			{ name: 'Sensitivity', token: 0x32 },
			{ name: 'TimeZone', token: 0x33 },
			{ name: 'GlobalObjId', token: 0x34 },
			{ name: 'ThreadTopic', token: 0x35 },
			{ name: 'MIMEData', token: 0x36 },
			{ name: 'MIMETruncated', token: 0x37 },
			{ name: 'MIMESize', token: 0x38 },
			{ name: 'InternetCPID', token: 0x39 },
			{ name: 'Flag', token: 0x3a },
			{ name: 'Status', token: 0x3b },
			{ name: 'ContentClass', token: 0x3c },
			{ name: 'FlagType', token: 0x3d },
			{ name: 'CompleteTime', token: 0x3e },
			{ name: 'DisallowNewTimeProposal', token: 0x3f }
		]
	},
	{
		name: 'AirNotify',
		tags: []
	},
	{
		name: 'Calendar',
		tags: [
			{ name: 'Timezone', token: 0x05 },
			{ name: 'AllDayEvent', token: 0x06 },
			{ name: 'Attendees', token: 0x07 },
			{ name: 'Attendee', token: 0x08 },
			{ name: 'Email', token: 0x09 },
			{ name: 'Name', token: 0x0a },
			{ name: 'Body', token: 0x0b },
			{ name: 'BodyTruncated', token: 0x0c },
			{ name: 'BusyStatus', token: 0x0d },
			{ name: 'Categories', token: 0x0e },
			{ name: 'Category', token: 0x0f },
			{ name: 'DtStamp', token: 0x11 },
			{ name: 'EndTime', token: 0x12 },
			{ name: 'Exception', token: 0x13 },
			{ name: 'Exceptions', token: 0x14 },
			{ name: 'Deleted', token: 0x15 },
			{ name: 'ExceptionStartTime', token: 0x16 },
			{ name: 'Location', token: 0x17 },
			{ name: 'MeetingStatus', token: 0x18 },
			{ name: 'OrganizerEmail', token: 0x19 },
			{ name: 'OrganizerName', token: 0x1a },
			{ name: 'Recurrence', token: 0x1b },
			{ name: 'Type', token: 0x1c },
			{ name: 'Until', token: 0x1d },
			{ name: 'Occurrences', token: 0x1e },
			{ name: 'Interval', token: 0x1f },
			{ name: 'DayOfWeek', token: 0x20 },
			{ name: 'DayOfMonth', token: 0x21 },
			{ name: 'WeekOfMonth', token: 0x22 },
			{ name: 'MonthOfYear', token: 0x23 },
			{ name: 'Reminder', token: 0x24 },
			{ name: 'Sensitivity', token: 0x25 },
			{ name: 'Subject', token: 0x26 },
			{ name: 'StartTime', token: 0x27 },
			{ name: 'UID', token: 0x28 },
			{ name: 'AttendeeStatus', token: 0x29 },
			{ name: 'AttendeeType', token: 0x2a },
			{ name: 'DisallowNewTimeProposal', token: 0x33 },
			{ name: 'ResponseRequested', token: 0x34 },
			{ name: 'AppointmentReplyTime', token: 0x35 },
			{ name: 'ResponseType', token: 0x36 },
			{ name: 'CalendarType', token: 0x37 },
			{ name: 'IsLeapMonth', token: 0x38 },
			{ name: 'FirstDayOfWeek', token: 0x39 },
			{ name: 'OnlineMeetingConfLink', token: 0x3a },
			{ name: 'OnlineMeetingExternalLink', token: 0x3b },
			{ name: 'ClientUid', token: 0x3c }
		]
	},
	{
		name: 'Move',
		tags: [
			{ name: 'MoveItems', token: 0x05 },
			{ name: 'Move', token: 0x06 },
			{ name: 'SrcMsgId', token: 0x07 },
			{ name: 'SrcFldId', token: 0x08 },
			{ name: 'DstFldId', token: 0x09 },
			{ name: 'Response', token: 0x0a },
			{ name: 'Status', token: 0x0b },
			{ name: 'DstMsgId', token: 0x0c }
		]
	},
	{
		name: 'GetItemEstimate',
		tags: [
			{ name: 'GetItemEstimate', token: 0x05 },
			{ name: 'Collections', token: 0x07 },
			{ name: 'Collection', token: 0x08 },
			{ name: 'Class', token: 0x09 },
			{ name: 'CollectionId', token: 0x0a },
			{ name: 'Estimate', token: 0x0c },
			{ name: 'Response', token: 0x0d },
			{ name: 'Status', token: 0x0e }
		]
	},
	{
		name: 'FolderHierarchy',
		tags: [
			{ name: 'Folders', token: 0x05 },
			{ name: 'Folder', token: 0x06 },
			{ name: 'DisplayName', token: 0x07 },
			{ name: 'ServerId', token: 0x08 },
			{ name: 'ParentId', token: 0x09 },
			{ name: 'Type', token: 0x0a },
			{ name: 'Status', token: 0x0c },
			{ name: 'Changes', token: 0x0e },
			{ name: 'Add', token: 0x0f },
			{ name: 'Delete', token: 0x10 },
			{ name: 'Update', token: 0x11 },
			{ name: 'SyncKey', token: 0x12 },
			{ name: 'FolderCreate', token: 0x13 },
			{ name: 'FolderDelete', token: 0x14 },
			{ name: 'FolderUpdate', token: 0x15 },
			{ name: 'FolderSync', token: 0x16 },
			{ name: 'Count', token: 0x17 }
		]
	},
	{
		name: 'MeetingResponse',
		tags: [
			{ name: 'CalendarId', token: 0x05 },
			{ name: 'CollectionId', token: 0x06 },
			{ name: 'MeetingResponse', token: 0x07 },
			{ name: 'RequestId', token: 0x08 },
			{ name: 'Request', token: 0x09 },
			{ name: 'Result', token: 0x0a },
			{ name: 'Status', token: 0x0b },
			{ name: 'UserResponse', token: 0x0c },
			{ name: 'InstanceId', token: 0x0e },
			{ name: 'SendResponse', token: 0x12 }
		]
	},
	{
		name: 'Tasks',
		tags: [
			{ name: 'Body', token: 0x05 },
			{ name: 'BodySize', token: 0x06 },
			{ name: 'BodyTruncated', token: 0x07 },
			{ name: 'Categories', token: 0x08 },
			{ name: 'Category', token: 0x09 },
			{ name: 'Complete', token: 0x0a },
			{ name: 'DateCompleted', token: 0x0b },
			{ name: 'DueDate', token: 0x0c },
			{ name: 'UtcDueDate', token: 0x0d },
			{ name: 'Importance', token: 0x0e },
			{ name: 'Recurrence', token: 0x0f },
			{ name: 'Type', token: 0x10 },
			{ name: 'Start', token: 0x11 },
			{ name: 'Until', token: 0x12 },
			{ name: 'Occurrences', token: 0x13 },
			{ name: 'Interval', token: 0x14 },
			{ name: 'DayOfMonth', token: 0x15 },
			{ name: 'DayOfWeek', token: 0x16 },
			{ name: 'WeekOfMonth', token: 0x17 },
			{ name: 'MonthOfYear', token: 0x18 },
			{ name: 'Regenerate', token: 0x19 },
			{ name: 'DeadOccur', token: 0x1a },
			{ name: 'ReminderSet', token: 0x1b },
			{ name: 'ReminderTime', token: 0x1c },
			{ name: 'Sensitivity', token: 0x1d },
			{ name: 'StartDate', token: 0x1e },
			{ name: 'UtcStartDate', token: 0x1f },
			{ name: 'Subject', token: 0x20 },
			{ name: 'OrdinalDate', token: 0x22 },
			{ name: 'SubOrdinalDate', token: 0x23 },
			{ name: 'CalendarType', token: 0x24 },
			{ name: 'IsLeapMonth', token: 0x25 },
			{ name: 'FirstDayOfWeek', token: 0x26 }
		]
	},
	{
		name: 'ResolveRecipients',
		tags: [
			{ name: 'ResolveRecipients', token: 0x05 },
			{ name: 'Response', token: 0x06 },
			{ name: 'Status', token: 0x07 },
			{ name: 'Type', token: 0x08 },
			{ name: 'Recipient', token: 0x09 },
			{ name: 'DisplayName', token: 0x0a },
			{ name: 'EmailAddress', token: 0x0b },
			{ name: 'Certificates', token: 0x0c },
			{ name: 'Certificate', token: 0x0d },
			{ name: 'MiniCertificate', token: 0x0e },
			{ name: 'Options', token: 0x0f },
			{ name: 'To', token: 0x10 },
			{ name: 'CertificateRetrieval', token: 0x11 },
			{ name: 'RecipientCount', token: 0x12 },
			{ name: 'MaxCertificates', token: 0x13 },
			{ name: 'MaxAmbiguousRecipients', token: 0x14 },
			{ name: 'CertificateCount', token: 0x15 },
			{ name: 'Availability', token: 0x16 },
			{ name: 'StartTime', token: 0x17 },
			{ name: 'EndTime', token: 0x18 },
			{ name: 'MergedFreeBusy', token: 0x19 },
			{ name: 'Picture', token: 0x1a },
			{ name: 'MaxSize', token: 0x1b },
			{ name: 'Data', token: 0x1c },
			{ name: 'MaxPictures', token: 0x1d }
		]
	},
	{
		name: 'ValidateCert',
		tags: [
			{ name: 'ValidateCert', token: 0x05 },
			{ name: 'Certificates', token: 0x06 },
			{ name: 'Certificate', token: 0x07 },
			{ name: 'CertificateChain', token: 0x08 },
			{ name: 'CheckCRL', token: 0x09 },
			{ name: 'Status', token: 0x0a }
		]
	},
	{
		name: 'Contacts2',
		tags: [
			{ name: 'CustomerId', token: 0x05 },
			{ name: 'GovernmentId', token: 0x06 },
			{ name: 'IMAddress', token: 0x07 },
			{ name: 'IMAddress2', token: 0x08 },
			{ name: 'IMAddress3', token: 0x09 },
			{ name: 'ManagerName', token: 0x0a },
			{ name: 'CompanyMainPhone', token: 0x0b },
			{ name: 'AccountName', token: 0x0c },
			{ name: 'NickName', token: 0x0d },
			{ name: 'MMS', token: 0x0e }
		]
	},
	{
		name: 'Ping',
		tags: [
			{ name: 'Ping', token: 0x05 },
			{ name: 'Status', token: 0x07 },
			{ name: 'HeartbeatInterval', token: 0x08 },
			{ name: 'Folders', token: 0x09 },
			{ name: 'Folder', token: 0x0a },
			{ name: 'Id', token: 0x0b },
			{ name: 'Class', token: 0x0c },
			{ name: 'MaxFolders', token: 0x0d }
		]
	},
	{
		name: 'Provision',
		tags: [
			{ name: 'Provision', token: 0x05 },
			{ name: 'Policies', token: 0x06 },
			{ name: 'Policy', token: 0x07 },
			{ name: 'PolicyType', token: 0x08 },
			{ name: 'PolicyKey', token: 0x09 },
			{ name: 'Data', token: 0x0a },
			{ name: 'Status', token: 0x0b },
			{ name: 'RemoteWipe', token: 0x0c },
			{ name: 'EASProvisionDoc', token: 0x0d },
			{ name: 'DevicePasswordEnabled', token: 0x0e },
			{ name: 'AlphanumericDevicePasswordRequired', token: 0x0f },
			{ name: 'RequireStorageCardEncryption', token: 0x10 },
			{ name: 'PasswordRecoveryEnabled', token: 0x11 },
			{ name: 'AttachmentsEnabled', token: 0x13 },
			{ name: 'MinDevicePasswordLength', token: 0x14 },
			{ name: 'MaxInactivityTimeDeviceLock', token: 0x15 },
			{ name: 'MaxDevicePasswordFailedAttempts', token: 0x16 },
			{ name: 'MaxAttachmentSize', token: 0x17 },
			{ name: 'AllowSimpleDevicePassword', token: 0x18 },
			{ name: 'DevicePasswordExpiration', token: 0x19 },
			{ name: 'DevicePasswordHistory', token: 0x1a },
			{ name: 'AllowStorageCard', token: 0x1b },
			{ name: 'AllowCamera', token: 0x1c },
			{ name: 'RequireDeviceEncryption', token: 0x1d },
			{ name: 'AllowUnsignedApplications', token: 0x1e },
			{ name: 'AllowUnsignedInstallationPackages', token: 0x1f },
			{ name: 'MinDevicePasswordComplexCharacters', token: 0x20 },
			{ name: 'AllowWiFi', token: 0x21 },
			{ name: 'AllowTextMessaging', token: 0x22 },
			{ name: 'AllowPOPIMAPEmail', token: 0x23 },
			{ name: 'AllowBluetooth', token: 0x24 },
			{ name: 'AllowIrDA', token: 0x25 },
			{ name: 'RequireManualSyncWhenRoaming', token: 0x26 },
			{ name: 'AllowDesktopSync', token: 0x27 },
			{ name: 'MaxCalendarAgeFilter', token: 0x28 },
			{ name: 'AllowHTMLEmail', token: 0x29 },
			{ name: 'MaxEmailAgeFilter', token: 0x2a },
			{ name: 'MaxEmailBodyTruncationSize', token: 0x2b },
			{ name: 'MaxEmailHTMLBodyTruncationSize', token: 0x2c },
			{ name: 'RequireSignedSMIMEMessages', token: 0x2d },
			{ name: 'RequireEncryptedSMIMEMessages', token: 0x2e },
			{ name: 'RequireSignedSMIMEAlgorithm', token: 0x2f },
			{ name: 'RequireEncryptionSMIMEAlgorithm', token: 0x30 },
			{ name: 'AllowSMIMEEncryptionAlgorithmNegotiation', token: 0x31 },
			{ name: 'AllowSMIMESoftCerts', token: 0x32 },
			{ name: 'AllowBrowser', token: 0x33 },
			{ name: 'AllowConsumerEmail', token: 0x34 },
			{ name: 'AllowRemoteDesktop', token: 0x35 },
			{ name: 'AllowInternetSharing', token: 0x36 },
			{ name: 'UnapprovedInROMApplicationList', token: 0x37 },
			{ name: 'ApplicationName', token: 0x38 },
			{ name: 'ApprovedApplicationList', token: 0x39 },
			{ name: 'Hash', token: 0x3a }
		]
	},
	{
		name: 'Search',
		tags: [
			{ name: 'Search', token: 0x05 },
			{ name: 'Store', token: 0x07 },
			{ name: 'Name', token: 0x08 },
			{ name: 'Query', token: 0x09 },
			{ name: 'Options', token: 0x0a },
			{ name: 'Range', token: 0x0b },
			{ name: 'Status', token: 0x0c },
			{ name: 'Response', token: 0x0d },
			{ name: 'Result', token: 0x0e },
			{ name: 'Properties', token: 0x0f },
			{ name: 'Total', token: 0x10 },
			{ name: 'EqualTo', token: 0x11 },
			{ name: 'Value', token: 0x12 },
			{ name: 'And', token: 0x13 },
			{ name: 'Or', token: 0x14 },
			{ name: 'FreeText', token: 0x15 },
			{ name: 'DeepTraversal', token: 0x17 },
			{ name: 'LongId', token: 0x18 },
			{ name: 'RebuildResults', token: 0x19 },
			{ name: 'LessThan', token: 0x1a },
			{ name: 'GreaterThan', token: 0x1b },
			{ name: 'UserName', token: 0x1e },
			{ name: 'Password', token: 0x1f },
			{ name: 'ConversationId', token: 0x20 },
			{ name: 'Picture', token: 0x21 },
			{ name: 'MaxSize', token: 0x22 },
			{ name: 'MaxPictures', token: 0x23 }
		]
	},
	{
		name: 'GAL',
		tags: [
			{ name: 'DisplayName', token: 0x05 },
			{ name: 'Phone', token: 0x06 },
			{ name: 'Office', token: 0x07 },
			{ name: 'Title', token: 0x08 },
			{ name: 'Company', token: 0x09 },
			{ name: 'Alias', token: 0x0a },
			{ name: 'FirstName', token: 0x0b },
			{ name: 'LastName', token: 0x0c },
			{ name: 'HomePhone', token: 0x0d },
			{ name: 'MobilePhone', token: 0x0e },
			{ name: 'EmailAddress', token: 0x0f },
			{ name: 'Picture', token: 0x10 },
			{ name: 'Status', token: 0x11 },
			{ name: 'Data', token: 0x12 }
		]
	},
	{
		name: 'AirSyncBase',
		tags: [
			{ name: 'BodyPreference', token: 0x05 },
			{ name: 'Type', token: 0x06 },
			{ name: 'TruncationSize', token: 0x07 },
			{ name: 'AllOrNone', token: 0x08 },
			{ name: 'Body', token: 0x0a },
			{ name: 'Data', token: 0x0b },
			{ name: 'EstimatedDataSize', token: 0x0c },
			{ name: 'Truncated', token: 0x0d },
			{ name: 'Attachments', token: 0x0e },
			{ name: 'Attachment', token: 0x0f },
			{ name: 'DisplayName', token: 0x10 },
			{ name: 'FileReference', token: 0x11 },
			{ name: 'Method', token: 0x12 },
			{ name: 'ContentId', token: 0x13 },
			{ name: 'ContentLocation', token: 0x14 },
			{ name: 'IsInline', token: 0x15 },
			{ name: 'NativeBodyType', token: 0x16 },
			{ name: 'ContentType', token: 0x17 },
			{ name: 'Preview', token: 0x18 },
			{ name: 'BodyPartPreference', token: 0x19 },
			{ name: 'BodyPart', token: 0x1a },
			{ name: 'Status', token: 0x1b },
			{ name: 'Add', token: 0x1c },
			{ name: 'Delete', token: 0x1d },
			{ name: 'ClientId', token: 0x1e },
			{ name: 'Content', token: 0x1f },
			{ name: 'Location', token: 0x20 },
			{ name: 'Annotation', token: 0x21 },
			{ name: 'Street', token: 0x22 },
			{ name: 'City', token: 0x23 },
			{ name: 'State', token: 0x24 },
			{ name: 'Country', token: 0x25 },
			{ name: 'PostalCode', token: 0x26 },
			{ name: 'Latitude', token: 0x27 },
			{ name: 'Longitude', token: 0x28 },
			{ name: 'Accuracy', token: 0x29 },
			{ name: 'Altitude', token: 0x2a },
			{ name: 'AltitudeAccuracy', token: 0x2b },
			{ name: 'LocationUri', token: 0x2c },
			{ name: 'InstanceId', token: 0x2d }
		]
	},
	{
		name: 'Settings',
		tags: [
			{ name: 'Settings', token: 0x05 },
			{ name: 'Status', token: 0x06 },
			{ name: 'Get', token: 0x07 },
			{ name: 'Set', token: 0x08 },
			{ name: 'Oof', token: 0x09 },
			{ name: 'OofState', token: 0x0a },
			{ name: 'StartTime', token: 0x0b },
			{ name: 'EndTime', token: 0x0c },
			{ name: 'OofMessage', token: 0x0d },
			{ name: 'AppliesToInternal', token: 0x0e },
			{ name: 'AppliesToExternalKnown', token: 0x0f },
			{ name: 'AppliesToExternalUnknown', token: 0x10 },
			{ name: 'Enabled', token: 0x11 },
			{ name: 'ReplyMessage', token: 0x12 },
			{ name: 'BodyType', token: 0x13 },
			{ name: 'DevicePassword', token: 0x14 },
			{ name: 'Password', token: 0x15 },
			{ name: 'DeviceInformation', token: 0x16 },
			{ name: 'Model', token: 0x17 },
			{ name: 'IMEI', token: 0x18 },
			{ name: 'FriendlyName', token: 0x19 },
			{ name: 'OS', token: 0x1a },
			{ name: 'OSLanguage', token: 0x1b },
			{ name: 'PhoneNumber', token: 0x1c },
			{ name: 'UserInformation', token: 0x1d },
			{ name: 'EmailAddresses', token: 0x1e },
			{ name: 'SMTPAddress', token: 0x1f },
			{ name: 'UserAgent', token: 0x20 },
			{ name: 'EnableOutboundSMS', token: 0x21 },
			{ name: 'MobileOperator', token: 0x22 },
			{ name: 'PrimarySmtpAddress', token: 0x23 },
			{ name: 'Accounts', token: 0x24 },
			{ name: 'Account', token: 0x25 },
			{ name: 'AccountId', token: 0x26 },
			{ name: 'AccountName', token: 0x27 },
			{ name: 'UserDisplayName', token: 0x28 },
			{ name: 'SendDisabled', token: 0x29 },
			{ name: 'RightsManagementInformation', token: 0x2b }
		]
	},
	{
		name: 'DocumentLibrary',
		tags: [
			{ name: 'LinkId', token: 0x05 },
			{ name: 'DisplayName', token: 0x06 },
			{ name: 'IsFolder', token: 0x07 },
			{ name: 'CreationDate', token: 0x08 },
			{ name: 'LastModifiedDate', token: 0x09 },
			{ name: 'IsHidden', token: 0x0a },
			{ name: 'ContentLength', token: 0x0b },
			{ name: 'ContentType', token: 0x0c }
		]
	},
	{
		name: 'ItemOperations',
		tags: [
			{ name: 'ItemOperations', token: 0x05 },
			{ name: 'Fetch', token: 0x06 },
			{ name: 'Store', token: 0x07 },
			{ name: 'Options', token: 0x08 },
			{ name: 'Range', token: 0x09 },
			{ name: 'Total', token: 0x0a },
			{ name: 'Properties', token: 0x0b },
			{ name: 'Data', token: 0x0c },
			{ name: 'Status', token: 0x0d },
			{ name: 'Response', token: 0x0e },
			{ name: 'Version', token: 0x0f },
			{ name: 'Schema', token: 0x10 },
			{ name: 'Part', token: 0x11 },
			{ name: 'EmptyFolderContents', token: 0x12 },
			{ name: 'DeleteSubFolders', token: 0x13 },
			{ name: 'UserName', token: 0x14 },
			{ name: 'Password', token: 0x15 },
			{ name: 'Move', token: 0x16 },
			{ name: 'DstFldId', token: 0x17 },
			{ name: 'ConversationId', token: 0x18 },
			{ name: 'MoveAlways', token: 0x19 }
		]
	},
	{
		name: 'ComposeMail',
		tags: [
			{ name: 'SendMail', token: 0x05 },
			{ name: 'SmartForward', token: 0x06 },
			{ name: 'SmartReply', token: 0x07 },
			{ name: 'SaveInSentItems', token: 0x08 },
			{ name: 'ReplaceMime', token: 0x09 },
			{ name: 'Source', token: 0x0b },
			{ name: 'FolderId', token: 0x0c },
			{ name: 'ItemId', token: 0x0d },
			{ name: 'LongId', token: 0x0e },
			{ name: 'InstanceId', token: 0x0f },
			{ name: 'Mime', token: 0x10 },
			{ name: 'ClientId', token: 0x11 },
			{ name: 'Status', token: 0x12 },
			{ name: 'AccountId', token: 0x13 },
			{ name: 'Forwardees', token: 0x15 },
			{ name: 'Forwardee', token: 0x16 },
			{ name: 'ForwardeeName', token: 0x17 },
			{ name: 'ForwardeeEmail', token: 0x18 }
		]
	},
	{
		name: 'Email2',
		tags: [
			{ name: 'UmCallerID', token: 0x05 },
			{ name: 'UmUserNotes', token: 0x06 },
			{ name: 'UmAttDuration', token: 0x07 },
			{ name: 'UmAttOrder', token: 0x08 },
			{ name: 'ConversationId', token: 0x09 },
			{ name: 'ConversationIndex', token: 0x0a },
			{ name: 'LastVerbExecuted', token: 0x0b },
			{ name: 'LastVerbExecutionTime', token: 0x0c },
			{ name: 'ReceivedAsBcc', token: 0x0d },
			{ name: 'Sender', token: 0x0e },
			{ name: 'CalendarType', token: 0x0f },
			{ name: 'IsLeapMonth', token: 0x10 },
			{ name: 'AccountId', token: 0x11 },
			{ name: 'FirstDayOfWeek', token: 0x12 },
			{ name: 'MeetingMessageType', token: 0x13 },
			{ name: 'IsDraft', token: 0x15 },
			{ name: 'Bcc', token: 0x16 },
			{ name: 'Send', token: 0x17 }
		]
	},
	{
		name: 'Notes',
		tags: [
			{ name: 'Subject', token: 0x05 },
			{ name: 'MessageClass', token: 0x06 },
			{ name: 'LastModifiedDate', token: 0x07 },
			{ name: 'Categories', token: 0x08 },
			{ name: 'Category', token: 0x09 }
		]
	},
	{
		name: 'RightsManagement',
		tags: [
			{ name: 'RightsManagementSupport', token: 0x05 },
			{ name: 'RightsManagementTemplates', token: 0x06 },
			{ name: 'RightsManagementTemplate', token: 0x07 },
			{ name: 'RightsManagementLicense', token: 0x08 },
			{ name: 'EditAllowed', token: 0x09 },
			{ name: 'ReplyAllowed', token: 0x0a },
			{ name: 'ReplyAllAllowed', token: 0x0b },
			{ name: 'ForwardAllowed', token: 0x0c },
			{ name: 'ModifyRecipientsAllowed', token: 0x0d },
			{ name: 'ExtractAllowed', token: 0x0e },
			{ name: 'PrintAllowed', token: 0x0f },
			{ name: 'ExportAllowed', token: 0x10 },
			{ name: 'ProgrammaticAccessAllowed', token: 0x11 },
			{ name: 'Owner', token: 0x12 },
			{ name: 'ContentExpiryDate', token: 0x13 },
			{ name: 'TemplateID', token: 0x14 },
			{ name: 'TemplateName', token: 0x15 },
			{ name: 'TemplateDescription', token: 0x16 },
			{ name: 'ContentOwner', token: 0x17 },
			{ name: 'RemoveRightsManagementProtection', token: 0x18 }
		]
	}
];
